name: develop_ci_cd
on: 
  push:
    branches: [ "develop"]
  pull_request:
    branches: [ "develop"]
jobs:
  develop_ci_cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Setup
        run: npm ci

      - name: Test
        run: |
            npm run test-headless 
      
      - name: build react
        run: npm run build
          
      - name: download, run httpd image, container name serving_base
        run: |
          docker run -d --name serving_base httpd
          
      - name: Copy React build to container
        run: |
         docker cp dist/testing-calculator/. serving_base:/usr/local/apache2/htdocs/
          
      - name: Build the custom Docker image
        run: docker commit --change "ENV MODEL_NAME ${{secrets.MODEL_NAME}}" serving_base ${{secrets.DOCKER_USER}}/${{secrets.MODEL_NAME}}:${{github.sha}}

      - name: show docker images
        run: docker images
        ##

      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
          
      - name: Docker Push
        run: docker push ${{secrets.DOCKER_USER}}/${{secrets.MODEL_NAME}}:${{github.sha}}
      
      - name: update docker user in k8 
        run: sed -i 's/{docker_user}/${{secrets.DOCKER_USER}}/g' manifests/k8s.yaml

      - name: update model name in k8 
        run: sed -i 's/{model_name}/${{secrets.MODEL_NAME}}/g' manifests/k8s.yaml

      - name: update _ by - 
        run: sed -i 's/_/-/g' manifests/k8s.yaml

      - name: update sha in k8
        run: sed -i 's/{github.sha}/${{github.sha}}/g' manifests/k8s.yaml

      - name: ls -la 
        run: cat manifests/k8s.yaml
      - uses: okteto/context@2.7.0
        with:
          token: ${{secrets.OKTETO_TOKEN }}

      - name: Deploy and Wait
        uses: okteto/actions/deploy@v1
        env:
          KUBECONFIG: ${{ steps.namespace.outputs.kubeconfig }}
        with:
          namespace: ${{secrets.OKTETO_NAMESPACE }}
          manifest: manifests/k8s.yaml
          tag: ${{ secrets.DOCKER_USERNAME }}/${{secrets.MODEL_NAME}}:${{github.sha}}
